### ISSUE TITLE
Negative genomic positions on left side of genome browser tracks

### ISSUE THREAD

**Issue by basvandenberg** [Multiplicom/axiom#102]
The genome browser tracks have a 'padding' left of the first genome position. When hovering the mouse over the reference genome track in this padding area, negative positions are shown in the tooltip.

![115619327-07b5b180-a2f4-11eb-8499-2a91cdc8a841](https://user-images.githubusercontent.com/1561851/115707655-5bb1ac00-a36f-11eb-9aed-66ead0bd7a39.png)

![115619343-0be1cf00-a2f4-11eb-999c-2c9b62eaea4e](https://user-images.githubusercontent.com/1561851/115707665-5e140600-a36f-11eb-8bde-28f2374a8e24.png)

Possible improvements/fixes:

- Do not show the tooltip for negative positions.
- Grey out the region with negative positions (or some other visual indication)
- Or don't use the padding at all (there is the same padding on the right side), is it necessary to include it?

**Comment by MichaelVyverman** [comment]
@joachimds to prioritise

**Comment by joachimds** [comment]
Low prio - can be tackled in next release.

It's only when hovering outside the screen that you see the negative position tooltip.

--> Don't show tooltip for negative position.
