### ISSUE TITLE
Remove dependency to CodeMirror 

### ISSUE THREAD

**Issue by goranvinterhalter** [Multiplicom/axiom#29]
This is a copy of Multiplicom/mastr_reporter#2089

**Comment by jeroencrappe** [comment]
@goranvinterhalter  If this means removing the usage of codemirror altogether, make sure to also include an update of the FSDS for this. (remove from SOUP) and/or replace by any alternative we might need.

**Comment by goranvinterhalter** [comment]
@jeroencrappe ok. I committed that change to Multiplicom/mastr_reporter#2089.
