### ISSUE TITLE
wheel scrolling causes issues in IE

### ISSUE THREAD

**Issue by MichaelVyverman** [Multiplicom/axiom#35]
Due to changes in #27

**Comment by goranvinterhalter** [comment]
The main issue was that IE didn't like using `originalEvent` for deltaY. Instead jQuery event must be used. 
Firefox bug addressed in #27 was solved by removing deprecated `DOMMouseScroll` and using only `mousewheelevent`.

`Mousewheelevent` is non-standard and it wold be better to replace it with `wheelevent` in the future.  Generally, these events are notoriously difficult to  standardize across OS and browser combinations and that should be addressed in a separate issue.
